# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20170329_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.DateTimeField(null=True, verbose_name=b'Appointment Date (YYYY-MM-DD HH:MM)'),
        ),
    ]
